spring:
  application:
    name: Blockchain Connector
  datasource:
    url: jdbc:h2:mem:dbtest
    driver-class-name: org.h2.Driver
    username: in2admin
    password: in2pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migrations
  security:
      user:
        name: in2test
        password: in2pass
logging:
  level:
    org.springframework.security: INFO
    es.in2.dome.blockchain.connector: DEBUG
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8080
app:
  openapi:
    dev-url: http://localhost:3311
    test-url: https://bkconntest.in2.es
    prod-url: https://bkconn.in2.es