# Application Configuration
openapi:
  server:
    url: http://localhost:8080
    description: Test Environment
  info:
    title: Blockchain Connector API
    version: 1.0.0-SNAPSHOT
    description: Blockchain Connector Software Solution
    termsOfService: https://example.com/terms-of-service
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
    contact:
      email: info@in2.es
      name: IN2, Ingeniería de la Información
      url: https://in2.es

# Operator Configuration
operator:
  organizationId: ${ORGANIZATION_ID}

# DLT Adapter Configuration
dlt-adapter:
  domain: http://localhost:8080

# Blockchain Configuration
blockchain:
  rpcAddress: https://red-t.alastria.io/v0/9461d9f4292b41230527d57ee90652a6
  userEthereumAddress: "0xb794f5ea0ba39494ce839613fffba74279579268"
  subscription:
    active: false
    notificationEndpoint: http://blockchain-connector-core:8080/notifications/dlt
    eventTypes: >
      ProductOffering

# Broker Adapter Configuration
broker-adapter:
  domain: http://broker-adapter:8080

# Context Broker Configuration
broker:
  externalDomain: https://<domain.org>/orion-ld
  internalDomain: http://localhost:1026

# NGSI Subscription Configuration
ngsi-subscription:
  notificationEndpoint: http://blockchain-connector-core:8080/notifications/broker
  entityTypes: >
    ProductOffering